name: First Workflow
# workflow_dispatch is an event that waits for the user to manually start the workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
